spring:
  application:
    name: zuul-service

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    blog:
        path: /xiaol/**
        url: http://www.baidu.com
    #用户服务
    user:
        path: /u/**
        serviceId: user-service
    #反馈服务
    feedback:
        path: /fb/**
        serviceId: feedback-service