spring:
  application:
    name: zuul-service

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    blog:
        path: /xiaol/**
        url: http://www.baidu.com
    user:
        path: /user/**
        serviceId: user-service
    feedback:
        path: /feedback/**
        serviceId: feedback-service